from backend.ml.domain_model_manager import (
    DomainModelManager
)


class Recommender:

    def __init__(self, model_dir="models"):

        self.manager = DomainModelManager(
            model_dir
        )

    # -----------------------------------------
    # Main recommendation method
    # -----------------------------------------

    def recommend(self, data):

        domain = self.manager.normalize_domain(
            data.get("Domain")
        )

        prediction = self.manager.predict(
            domain,
            data
        )

        failure_type = prediction[
            "failure_type"
        ]

        probability = prediction[
            "probability"
        ]

        class_probabilities = prediction[
            "class_probabilities"
        ]

        recommendations = self._recommend(
            domain,
            data,
            failure_type
        )

        actions = self._actions(
            domain,
            data,
            failure_type
        )

        return {
            "domain": domain,

            "prediction": {
                "failure_type": failure_type,
                "probability": probability
            },

            "probability": class_probabilities,

            "cluster": {
                "cluster": "Domain-specific"
            },

            "historical_analysis": {
                "domain": domain,
                "failure_types": {
                    failure_type: 1
                },
                "message": (
                    "Prediction generated by the "
                    "domain-specific ML model."
                )
            },

            "similar_failures": [],

            "recommendations": recommendations,

            "improvement_actions": actions
        }

    # -----------------------------------------
    # Safe numeric conversion
    # -----------------------------------------

    @staticmethod
    def _safe_float(value, default=0.0):

        if value is None:
            return default

        try:
            return float(value)

        except (TypeError, ValueError):
            return default

    # -----------------------------------------
    # Recommendations
    # -----------------------------------------

    def _recommend(
        self,
        domain,
        data,
        failure_type
    ):

        if domain == "Student":

            actions = []

            absences = self._safe_float(
                data.get("absences")
            )

            study = self._safe_float(
                data.get("studytime")
            )

            failures = self._safe_float(
                data.get("failures")
            )

            g2 = self._safe_float(
                data.get("G2")
            )

            if absences > 10:
                actions.append(
                    "Reduce avoidable absences."
                )

            if study < 3:
                actions.append(
                    "Increase study time."
                )

            if failures > 0:
                actions.append(
                    "Address previous academic failures."
                )

            if g2 < 10:
                actions.append(
                    "Improve academic performance."
                )

            if failure_type == "Passed":
                actions.append(
                    "Maintain the current study routine."
                )

            if not actions:
                actions.append(
                    "Maintain current performance."
                )

            return actions

        if domain == "Software":

            return [
                "Investigate the reported issue.",
                "Review technical dependencies.",
                "Review issue priority.",
                "Document the root cause.",
                "Monitor the issue after resolution."
            ]

        if domain == "Jobs":

            actions = []

            skills = self._safe_float(
                data.get("skills_match_score")
            )

            experience = self._safe_float(
                data.get("years_experience")
            )

            if skills < 50:
                actions.append(
                    "Improve skills relevant to the target role."
                )

            elif skills < 70:
                actions.append(
                    "Strengthen the current skill match."
                )

            else:
                actions.append(
                    "Maintain the current skill level."
                )

            if experience < 2:
                actions.append(
                    "Gain additional relevant experience."
                )

            actions.append(
                "Strengthen the resume with measurable achievements."
            )

            return actions

        if domain == "Projects":

            completion = self._safe_float(
                data.get("Completion")
            )

            if completion < 30:

                return [
                    "Review project schedule.",
                    "Identify blocked tasks.",
                    "Improve resource allocation.",
                    "Monitor project progress closely."
                ]

            if completion < 60:

                return [
                    "Increase project progress.",
                    "Address delayed activities.",
                    "Review remaining project tasks."
                ]

            return [
                "Maintain project progress.",
                "Monitor remaining activities.",
                "Address risks early."
            ]

        return [
            "Review the factors affecting the prediction."
        ]

    # -----------------------------------------
    # Improvement actions
    # -----------------------------------------

    def _actions(
        self,
        domain,
        data,
        failure_type
    ):

        if domain == "Student":

            return [
                "Improve academic performance",
                "Increase study time",
                "Reduce avoidable absences",
                "Review previous weak areas"
            ]

        if domain == "Software":

            return [
                "Investigate root cause",
                "Review dependencies",
                "Fix the reported issue",
                "Monitor after resolution"
            ]

        if domain == "Jobs":

            return [
                "Improve skill match",
                "Strengthen resume",
                "Build relevant experience",
                "Review skill gaps"
            ]

        if domain == "Projects":

            return [
                "Monitor completion",
                "Address delayed tasks",
                "Improve planning",
                "Review project risks"
            ]

        return [
            "Review important performance factors."
        ]